import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://xojdlpxyikajwnqtpoy.supabase.co'
const SUPABASE_ANON_KEY = 'TA_CLE_ANOeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvamRscHh5aWthanducXRweG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MzAyNzUsImV4cCI6MjA4OTEwNjI3NX0.-n3Rsy20QS_YKcaXhWL6zmSNbwrfsPUF2wgyOPjTCcs'

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)